# Generated by Django 5.1.3 on 2025-01-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_completed_at_task_created_at_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
